Vagrant.configure("2") do |config|

  # General configuration for all virtual machines
  config.vm.provider :virtualbox do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end
  config.vm.provision "shell", inline: <<-SHELL
  yum install -y puppet
SHELL
  # Common Puppet configuration
  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "site.pp"
    puppet.module_path    = "modules"
    puppet.options = "--verbose --debug"
  end

  # Database VM (often provisioned first)
  config.vm.define "db01" do |db01|
    db01.vm.box = "generic/centos8"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", bridge: "eno1", ip: "192.168.60.15"
  end

  # Memcached VM
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "generic/centos8"
    mc01.vm.hostname = "mc01"
    mc01.vm.network "private_network", bridge: "eno1", ip: "192.168.60.14"
  end

  # Tomcat app server VM
  config.vm.define "app01" do |app01|
    app01.vm.box = "generic/centos8"
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", bridge: "eno1", ip: "192.168.60.12"
  end

  # Nginx web server VM (often provisioned last)
  config.vm.define "web01" do |web01|
    web01.vm.box = "generic/centos8"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", bridge: "eno1" , ip: "192.168.60.11"
  end

end

